
export const myCollection = [
  {
    id: '111',
    name: 'test1',
    details: 'my details test 1',
    supply: 'test supply 1',
    price_d: 324,
    price_f: 222,
    image: '',
    amount: 10,
  },
  {
    id: '222',
    name: 'test2',
    details: 'my details test 2',
    supply: 'test supply 2',
    price_d: 124,
    price_f: 32,
    image: '',
    amount: 10,
  },
  {
    id: '333',
    name: 'test3',
    details: 'my details test 3',
    supply: 'test supply 3',
    price_d: 124,
    price_f: 32,
    image: '',
    amount: 21,
  },
  {
    id: '444',
    name: 'test4',
    details: 'my details test 4',
    supply: 'test supply 4',
    price_d: 124,
    price_f: 32,
    image: '',
    amount: 12,
  },
  {
    id: '555',
    name: 'test5',
    details: 'my details test 5',
    supply: 'test supply 5',
    price_d: 124,
    price_f: 32,
    image: '',
    amount: 14,
  },
]
